# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('guardian', models.CharField(max_length=512)),
                ('doctor_refer', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.CharField(blank=True, max_length=512, null=True)),
                ('mobile', models.BigIntegerField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('cost', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('company', models.CharField(max_length=512)),
                ('supply_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(blank=True, max_length=512, null=True)),
                ('company', models.CharField(max_length=512)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('supply_date', models.DateField()),
                ('supplier_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='Admin.Medicine')),
            ],
        ),
    ]
