# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-18 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(choices=[(b'Tablet', b'Tablet'), (b'Syrup', b'Syrup'), (b'Not Define', b'Not Define')], default=b'Not Define', max_length=25),
        ),
    ]
