# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=b'doctor_images'),
        ),
    ]
